require 'rake/clean'
require_relative 'download'
require 'rbconfig'

EXE='TimeEnforcer.exe'

def is_windows?
	return (RbConfig::CONFIG['host_os'] =~ /mswin|mingw|cygwin/)
end

if is_windows?
DOTNETRUNTIME=''
NUGET='c:\bin\nuget.exe'
else
	DOTNETRUNTIME='mono --runtime=v4.0'
end
CSC='"C:\Windows\Microsoft.NET\Framework64\v4.0.30319\csc.exe"'

CLOBBER.include(EXE)

task :default => ["test"]

SRC = FileList['*.cs'].gsub(%r|/|, "\\")

file EXE => SRC do
  sh "copy package\\NUnitLite\\lib\\net45\\nunitlite.dll ."
  sh "#{CSC} /target:exe /out:#{EXE} /r:nunitlite.dll #{SRC}"
end

task "test" => ["nuget", EXE] do
  sh "#{DOTNETRUNTIME} #{EXE}"
end

task "nuget" do
  download_with_progress 'http://nuget.org:80/nuget.exe'
  sh "set EnableNuGetPackageRestore=true & #{DOTNETRUNTIME} #{NUGET} install packages.config -o package -ExcludeVersion"
end
