require 'rake/clean'

EXE='TimeEnforcer.exe'

CLOBBER.include(EXE)

task :default => ["test"]

SRC = FileList['*.cs'].gsub(%r|/|, "\\")

file EXE => SRC do
  sh "cp package/NUnitLite/lib/net45/nunitlite.dll ."
  sh "mcs /target:exe /out:#{EXE} /r:nunitlite.dll #{SRC}"
end

task "test" => ["nuget", EXE] do
  sh "mono --runtime=v4.0 #{EXE}"
end

task "nuget" do
  sh "mono --runtime=v4.0 ~/bin/Nuget.exe install packages.config -o package -ExcludeVersion"
end
